[package]
name = "bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
assert2 = "0.3.13"
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
glob = "0.3.1"
log = "0.4.20"
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
url = { version = "2.5.0", features = ["serde"] }
env_logger = "0.11.2"
die-exit = { version = "0.5.0", features = ["red"] }
thiserror = "1.0.58"
once_cell = "1.19.0"
terminal-menu = "3.0.0"
